---
apache_log_path:
  rhel: '/var/log/httpd'
  ubuntu: '/var/log/apache2'
apache:
  package_name:
    ubuntu: apache2
    rhel: httpd
  service_name:
    ubuntu: apache2
    rhel: httpd
  modules:
    ubuntu:
      - libapache2-mod-proxy-html
    ubuntu2:
      - libapache2-mod-wsgi
      - libapache2-mod-uwsgi
      - libapache2-mod-proxy-uwsgi
    rhel:
      - mod_wsgi
      - mod_proxy_uwsgi
  listen: []
  logs:
    - paths:
        - "{{ apache_log_path[ursula_os] }}/access.log"
      fields:
        # type: <custom type defined in receiving Logstash>
        tags: apache_access
    - paths:
        -  "{{ apache_log_path[ursula_os] }}/error.log"
      fields:
        # type: <custom type defined in receiving Logstash>
        tags: apache_error
